Platform/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('explorar_eventos/', views.explorar_eventos, name='explorar_eventos'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/remover_user_img/', views.remover_user_img, name='remover_user_img'),
    path('ver_perfil/<int:user_id>/', views.ver_perfil, name='ver_perfil'),
    path('ver_eventos_participando/<int:user_id>/', views.ver_eventos_participando, name='ver_eventos_participando'),
    path('ver_eventos_organizando/<int:user_id>/', views.ver_eventos_organizando, name='ver_eventos_organizando'),
    re_path('notificacoes/', include('notifications.urls', namespace='notifications')),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secretadmin/', admin.site.urls),
    path('', include('Platform.urls')),
    path('eventos/', include('eventos.urls')),
    path('accounts/', include('account_manager.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Platform/models.py
from django.db import models

# Create your models here.

Platform/forms.py
from django import forms
from account_manager.models import User, PhoneNumber, phone_number_validators

class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ['phone_number']
        widgets = {
            'phone_number': forms.TextInput(attrs={'class': 'form-control custom-form-width', 'placeholder': '+00 00000-0000', 'style': 'display: inline-block;'}),
        }
        labels = {
            'phone_number': '',
            'DELETE': 'Remover'
        }
    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        phone_number_validators(phone_number)
        return phone_number


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'idade', 'user_img']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control custom-form-width', 'placeholder': 'Insira seu nome de usuário'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control custom-form-width', 'placeholder': 'Insira sua idade', 'required': 'required'}),
            'user_img': forms.ClearableFileInput(attrs={'class': 'form-control custom-form-width'}),
        }
        labels = {
            'username': 'Nome de usuário',
            'idade': 'Idade',
            'user_img': 'Imagem de perfil',
        }
        
    def clean_idade(self):
        idade = self.cleaned_data['idade']
        if idade:
            if idade >= 14:
                return idade
            self.add_error('idade', 'Menores de 14 anos não podem se cadastrar.')
            return
        self.add_error('idade', 'É necessário informar a idade.')

account_manager/forms.py
from django import forms
from .models import phone_number_validators
from allauth.account.forms import SignupForm, LoginForm, ChangePasswordForm, ResetPasswordForm, ResetPasswordKeyForm, SetPasswordForm
from .models import User

class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha',})
        self.fields['password1'].label = 'Senha:'
        self.fields['password2'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha (novamente)',})
        self.fields['password2'].label = 'Confirmar Senha:'
        self.fields['username'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Nome de usuário'})
        self.fields['username'].label = 'Nome de Usuário:'
        self.fields['email'].widget.attrs.update({'class': 'form-control custom-form-width', "placeholder": "Endereço de email"})
        self.fields['email'].label = 'Endereço de email:'
        
    
    idade = forms.IntegerField(required=True, label='Idade:', widget=forms.NumberInput(attrs={'class': 'form-control custom-form-width', 'placeholder': 'Idade'}))
    # Não obrigatórios
    phone_number = forms.CharField(required=False, label='Número de telefone:', max_length=14, validators=[phone_number_validators], widget=forms.TextInput(attrs={'id': 'id_phone_number', 'class': 'form-control custom-form-width', 'placeholder': '+00 00000-0000'}))
    #
    field_order = ['username', 'email', 'idade', 'password1', 'password2', 'user_img']

    def clean_email(self):
        email = self.cleaned_data['email']
        if email:
            if User.objects.filter(email=email).exists():
                self.add_error('email', 'Alguém já se registrou com este endereço de e-mail.')
            else:
                return email

    def clean_idade(self):
        idade = self.cleaned_data["idade"]
        if idade:
            if idade < 14:
                self.add_error('idade', 'Menores de 14 anos não podem se cadastrar.')
            else:
                return idade
    # TODO test this in test_views
    def save(self, request):
        user = User.objects.create_user(
        email=self.cleaned_data['email'],
        username=self.cleaned_data['username'],
        password=self.cleaned_data['password1'],
        idade=self.cleaned_data['idade'],
        )
        user.phonenumber_set.create(phone_number=self.cleaned_data['phone_number'])
        return user

class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({'class': 'form-control custom-form-width', "placeholder": "Endereço de email"})
        self.fields['login'].label = 'Endereço de email:'
        self.fields['password'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha',})
        self.fields['password'].label = 'Senha:'

class CustomChangePasswordForm(ChangePasswordForm):

    def __init__(self, *args, **kwargs):
        super(CustomChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['oldpassword'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha atual',})
        self.fields['password1'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha nova',})
        self.fields['password2'].widget.attrs.update({'class': 'form-control custom-form-width', 'placeholder': 'Senha nova (novamente)',})

    def clean_oldpassword(self):
        if not self.user.check_password(self.cleaned_data.get("oldpassword")):
            raise forms.ValidationError('A senha atual está incorreta.')
        return self.cleaned_data["oldpassword"]
    
class CustomResetPasswordForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control custom-form-width'})

class CustomResetPasswordKeyForm(ResetPasswordKeyForm):
    def __init__(self, *ars, **kwargs):
        super(CustomResetPasswordKeyForm, self).__init__(*ars, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control custom-form-width'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control custom-form-width'})

class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *ars, **kwargs):
        super(CustomSetPasswordForm, self).__init__(*ars, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control custom-form-width'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control custom-form-width'})

Platform/views.py
from django.shortcuts import render, redirect
from eventos.models import Event, Category
from datetime import timedelta
from django.utils import timezone
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ProfileForm, PhoneNumberForm
from django import forms
from account_manager.models import User, PhoneNumber, DEFAULT_USER_IMG
from django.contrib.messages import constants
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from Platform.utils import remove_obj_img

# Create your views here.
def home(request):
    num_featured_events = 6
    data_atual = timezone.now()
    # Para pegar os eventos que já passaram se o evento passou à apenas um dia
    featured_events = Event.objects.filter(final_date_time__gte=data_atual - timedelta(days=1)).annotate(qtd_part=Count('participants')).order_by('-qtd_part')[:num_featured_events]
    return render(request, 'home.html', {'events': featured_events})


def explorar_eventos(request):
    search = request.GET.get('search', '')
    select_category = request.GET.get('select_category')
    select_num_participants = request.GET.get('select_num_participants')
    select_start_date_time = request.GET.get('select_start_date_time')
    select_private = request.GET.get('select_private')
    select_free = request.GET.get('select_free')
    data_atual = timezone.now()
    # Para pegar os eventos que já passaram se o evento passou à apenas um dia
    events = Event.objects.filter(final_date_time__gte=data_atual - timedelta(days=1))
    categories = Category.objects.all()
    
    if search:
        events = events.filter(title__icontains=search)

    if select_category:
        events = events.filter(category_id=select_category)

    if select_start_date_time:
        match select_start_date_time:
            case 'today':
                events = events.filter(start_date_time__year=data_atual.year).filter(start_date_time__month=data_atual.month).filter(start_date_time__day=data_atual.day)
            case 'this_month':
                events = events.filter(start_date_time__month=data_atual.month)
            case 'next_month':
                events = events.filter(start_date_time__month=data_atual.month + 1)
            case 'this_year':
                events = events.filter(start_date_time__year=data_atual.year)

    if select_private:
        match select_private:
            case "true":
                events = events.filter(private=True)
            case "false":
                events = events.filter(private=False)

    if select_free:
        match select_free:
            case "true":
                events = events.filter(free=True)
            case "false":
                events = events.filter(free=False)

    if select_num_participants:
        match select_num_participants:
            case 'gt_10':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__gte=10)
            case 'lt_10':    
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__lte=10)
            case 'gt_20':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__gte=20)
            case 'lt_20':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__lte=20)
            case 'gt_50':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__gte=50)
            case 'lt_50':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__lte=50)
            case 'gt_100':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__gte=100)
            case 'lt_100':
                events = events.annotate(qtd_part=Count('participants')).filter(qtd_part__lte=100)
        
    page_num = request.GET.get('page', '1')
    event_paginator = Paginator(events, 24)
    try:
        page = event_paginator.page(page_num)
    except(EmptyPage, PageNotAnInteger):
        page = event_paginator.page(1)
    
    return render(request, 'explorar_eventos.html', {'page': page, 'categories':  categories, 'value_select_category': select_category})


@login_required
def perfil(request):
    user_img = request.user.user_img
    user_img_is_default = user_img == DEFAULT_USER_IMG
    if request.method == 'GET':
        phone_numbers = request.user.phonenumber_set.all()
        extra = 0
        for ex in range(3, -1, -1):
            if phone_numbers.count() == ex:
                extra = 3 - ex

        form_factory = forms.inlineformset_factory(User, PhoneNumber, form=PhoneNumberForm, extra=extra)

        form_filho = form_factory(instance=request.user)
        form = ProfileForm(instance=request.user)
        return render(request, 'perfil.html', {'form': form, 'form_filho': form_filho, 'user_img': user_img, 'user_img_is_default': user_img_is_default})
    elif request.method == 'POST':
        form_factory = forms.inlineformset_factory(User, PhoneNumber, form=PhoneNumberForm)
        form_filho = form_factory(request.POST, instance=request.user)
        form = ProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid() and form_filho.is_valid():
            formulario = form.save()
            form_filho.instance = formulario
            form_filho.save()
            messages.add_message(request, constants.SUCCESS, 'Alterações salvas.')
            return redirect('perfil')
        return render(request, 'perfil.html', {'form': form, 'form_filho': form_filho, 'user_img': user_img})

        
def ver_perfil(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        messages.add_message(request, constants.ERROR, 'Usuário não existe.')
        return redirect('home')
    qtd_events_organizing = Event.objects.filter(organizer=user).count()
    qtd_event_participanting = user.event_participants.all().count()
    return render(request, 'ver_perfil.html', {'user': user, 'qtd_events_organizing': qtd_events_organizing, 'qtd_event_participanting': qtd_event_participanting})


def ver_eventos_participando(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        messages.add_message(request, constants.ERROR, 'Usuário não existe.')
        return redirect('home')
    event_participanting = user.event_participants.filter(final_date_time__gte=timezone.now() - timedelta(days=1))
    return render(request, 'ver_eventos_participando.html', {'user': user, 'events_participanting': event_participanting})


def ver_eventos_organizando(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        messages.add_message(request, constants.ERROR, 'Usuário não existe.')
        return redirect('home')
    events_organizing = Event.objects.filter(organizer=user).filter(final_date_time__gte=timezone.now() - timedelta(days=1))
    return render(request, 'ver_eventos_organizando.html', {'user': user, 'events_organizing': events_organizing})

@login_required
def remover_user_img(request):
    message = {'type': 'constants.ERROR', 'content': 'conNão foi possível remover a imagem de usuário.'}
    if remove_obj_img(request.user, field_img_name='user_img'):
        message['type'] = constants.SUCCESS
        message['content'] = 'Imagem de usuário removida.'
    messages.add_message(request, message['type'], message['content'])    
    return redirect('perfil')

Platform/templates/home.html
{% extends 'base/base.html' %} 
{% load static %}


{% block head %}
  <link rel="stylesheet" href="{% static 'Platform/css/home.css' %}">
{% endblock %}

{% block title %} EventEase - Home {% endblock %}


{% block body %} 

  <header>
    <div class="container">
        <h1>EventEase - Organize e participe de eventos de maneira descomplicada e eficiente. </h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum sit totam animi debitis quam iste, voluptas qui molestiae doloribus nesciunt magni assumenda voluptates ea inventore. Quis ratione fuga enim hic.</p>
        
        {% if not request.user.is_authenticated %}
          <a href="{% url 'account_signup' %}" class="cta-button">Registre-se Agora</a>
          <a href="{% url 'account_login' %}" class="cta-button">Entrar</a>
        {% else %}
          <a href="{% url 'explorar_eventos' %}" class="cta-button">Explorar eventos</a>
        {% endif %}
    </div>
  </header>

{% if messages %}
  <br>
  <ul class="messages">
      {% for message in messages %}
        <div class="{{ message.tags }}" role="alert">
          {{ message }}
        </div>
      {% endfor %}
  </ul>
{% endif %}

<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">
    <h2 style="color: #f85a40;"><b>Eventos em Destaque</b></h2>
    <p>Confira os eventos mais populares. Para mais, acesse <a href="{% url 'explorar_eventos' %}">Explorar</a></p>

    <div class="row gy-4 posts-list">
      {% for event in events %}
      <div class="col-xl-4 col-md-6 custom-card">
        <article class=" {% if event.has_passed %}has_passed{% endif %}">
          <div class="post-img">  
            <img src="{{ event.event_banner.url }}" alt="" class="img-fluid custom-img-fluid">
          </div>
          <p class="post-category">
            {{ event.category }}
          </p>

          <h2 class="title">
            <a href="{% url 'ver_mais' event.id %}">{{ event.title }}</a>
          </h2>
          <p class="caracteristica-evento">{% if event.free %}Livre{% else %}+18{% endif %}</p>
          <p class="caracteristica-evento">{% if event.private %}Privado{% else %}Público{% endif %}</p>
          {% if event.has_passed %}<p style="color: red;">Evento já acabou...</p>{% endif %}

          <p class="n-participants"><a class="link" style="text-decoration: none;" href="{% url 'participantes' event.id %}"><i class="bi bi-person-fill"></i> {{ event.qtd_participants }}</a></p>
          <div class="d-flex align-items-center">
            <div class="post-meta">
              <p class="post-author-list">{{ event.organizer }}</p>
              <p class="post-date"> 
                <time datetime="{{ event.start_date_time }}">{{ event.start_date_time|date:"d/m/Y" }}</time>
              </p>
            </div>
          </div>
          <a href="{% url 'ver_mais' event.id %}" class="cta-button btn-uniq">Ver mais</a>
        </article>
      </div>

 {% empty %}
      <h1>Nenhum evento encontrado.</h1>

 {% endfor %}

 <div class="blog-pagination">
  <ul class="justify-content-center">

    {% if page.has_previous %}
      <li><a href="{% url 'explorar_eventos' %}?page={{ page.previous_page_number }}&search={{ request.GET.search }}&select_category={{ request.GET.select_category }}&select_num_participants={{ request.GET.select_num_participants }}&select_start_date_time={{ request.GET.select_start_date_time }}&select_private={{ request.GET.select_private }}&select_free={{ request.GET.select_free }}">Anterior</a></li>
    {% endif %}

    {% for num in page.paginator.page_range %}
      {% if num == page.number %}
        <li class="active"><a href="">{{ page.number }}</a></li>
      {% else %}
      <li><a href="{% url 'explorar_eventos' %}?page={{ num }}&search={{ request.GET.search }}&select_category={{ request.GET.select_category }}&select_num_participants={{ request.GET.select_num_participants }}&select_start_date_time={{ request.GET.select_start_date_time }}&select_private={{ request.GET.select_private }}&select_free={{ request.GET.select_free }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page.has_next %}
      <li><a href="{% url 'explorar_eventos' %}?page={{ page.next_page_number }}&search={{ request.GET.search }}&select_category={{ request.GET.select_category }}&select_num_participants={{ request.GET.select_num_participants }}&select_start_date_time={{ request.GET.select_start_date_time }}&select_private={{ request.GET.select_private }}&select_free={{ request.GET.select_free }}">Próxima</a></li>
    {% endif %}

  </ul>
</div><!-- End blog pagination -->

</div>
</section><!-- End Blog Section -->

</div>
</section><!-- End Blog Section -->
{% endblock %}

Platform/templates/perfil.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
    <style>
        .custom-container a{
            color: #f85a40;
            text-decoration: underline;

        }
        a:hover{
            color: #c54734;
            text-decoration:solid;
        }
        ul{
            margin: 0;
        }
    </style>
{% endblock %}

{% block title %}Perfil{% endblock %}

{% block body %}    

    <div class="container custom-container c-auth">
        <h1>Perfil</h1>
        {% if messages %}
        
        <ul class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}" role="alert">
                {{ message|safe }}
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        <hr>
        <form action="" method="post" enctype="multipart/form-data" class="row g-3">{% csrf_token %}
            <div class="mb-3">
                <label for="id_user_img">{{ form.user_img.label }}:</label> <br>
                <a href="{{ user_img.url }}">
                    <img class="value-img" src="{{ user_img.url }}">
                </a> 
            </div>
            <div class="mb-3">
                <div class="form-group">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        {% if not user_img_is_default %}
                        <a class="btn btn-danger delete-btn" href="{% url 'remover_user_img' %}" title='Remover imagem de usuário' >
                          <i class="bi bi-trash" style="color: white;"></i>
                        </a>
                        {% endif %}
                        {{ form.user_img }}
                      </div>
                    </div>
                  </div>
                {% if form.user_img.errors %}
                    <ul class="errorlist">
                        {% for error in form.user_img.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_username">{{ form.username.label }}:</label>
                {{ form.username }}

                {% if form.username.errors %}
                    <ul class="errorlist">
                        {% for error in form.username.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_idade">{{ form.idade.label }}:</label>
                {{ form.idade }}

                {% if form.idade.errors %}
                    <ul class="errorlist">
                        {% for error in form.idade.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <a href="{% url 'account_change_password' %}"><b>Mudar Senha</b></a>
            <hr>
            <label>Número de Telefone:</label>
            <div class="mb-3">
                {{ form_filho.management_form }}
                {% for form_ in form_filho %}
                    {% if forloop.first %}
                        <p class="form_">
                            {{ form_ }}
                        </p>
                    {% else %}
                        {% if form_.has_changed %}
                            <p class="form_">
                                {{ form_ }}
                            </p>
                        {% else %}
                            <div hidden class="hid-form">{{ form_ }}</div>
                        {% endif %}
                    {% endif %}
                    {% if forloop.last %} 
                        {% if not form_.has_changed %}
                            <button onclick="addNumber(this)" type="button">add número</button>
                        {% endif %}
                    {% endif %}
                {% endfor %}

            </div>
            <hr>
            <button type="submit" class="btn cta-button">Salvar</button>
        </form>
    </div>
{% endblock %}

{% block endbody %} 
<h1>nao si o qeu nao sei o que la</h1> 
<script>

let hiddens = document.getElementsByClassName('hid-form');
function addNumber(btn) {
    hidden = hiddens[0]
    hidden.removeAttribute('hidden')
    hidden.classList.remove('hid-form')
    
    hiddens = document.getElementsByClassName('hid-form');
    if (hiddens.length == 0){
        btn.remove()
    }
}
</script>
{% endblock %}

Platform/templates/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
    <style>
        .custom-container a{
            color: #f85a40;
            text-decoration: underline;

        }
        a:hover{
            color: #c54734;
            text-decoration:solid;
        }
        ul{
            margin: 0;
        }
    </style>
{% endblock %}

{% block 'title' %}Perfil{% endblock %}

{% block 'body' %}    

    <div class="container custom-container c-auth">
        <h1>Perfil</h1>
        {% if messages %}
        
        <ul class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}" role="alert">
                {{ message|safe }}
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        <hr>
        <form action="" method="post" enctype="multipart/form-data" class="row g-3">{% csrf_token %}
            <div class="mb-3">
                <label for="id_user_img">{{ form.user_img.label }}:</label> <br>
                <a href="{{ user_img.url }}">
                    <img class="value-img" src="{{ user_img.url }}">
                </a> 
            </div>
            <div class="mb-3">
                    {{ form.user_img }}
                {% if form.user_img.errors %}
                    <ul class="errorlist">
                        {% for error in form.user_img.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_username">{{ form.username.label }}:</label>
                {{ form.username }}

                {% if form.username.errors %}
                    <ul class="errorlist">
                        {% for error in form.username.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_idade">{{ form.idade.label }}:</label>
                {{ form.idade }}

                {% if form.idade.errors %}
                    <ul class="errorlist">
                        {% for error in form.idade.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <a href="{% url 'account_change_password' %}"><b>Mudar Senha</b></a>
            <hr>
            <label>Número de Telefone:</label>
            <div class="mb-3">
                {{ form_filho.management_form }}
                {% for form_ in form_filho %}
                    {% if forloop.first %}
                        <p class="form_">
                            {{ form_ }}
                        </p>
                    {% else %}
                        {% if form_.has_changed %}
                            <p class="form_">
                                {{ form_ }}
                            </p>
                        {% else %}
                            <p hidden class="hid-form">
                                {{ form_ }}
                            </p>
                        {% endif %}
                    {% endif %}
                    {% if forloop.last %} 
                        {% if not form_.has_changed %}
                            <button onclick="addNumber(this)" type="button">add número</button>
                        {% endif %}
                    {% endif %}
                {% endfor %}

            </div>
            <hr>
            <button type="submit" class="btn cta-button">Salvar</button>
        </form>
    </div>
{% endblock %}

{% block 'endbody' %}  
<script>

let hiddens = document.getElementsByClassName('hid-form');
function addNumber(btn) {
    hidden = hiddens[0]
    hidden.removeAttribute('hidden')
    hidden.classList.remove('hid-form')
    
    hiddens = document.getElementsByClassName('hid-form');
    if (hiddens.length == 0){
        btn.remove()
    }
}
</script>
{% endblock %}

Platform/templates/ver_eventos_organizando.html
{% extends "base/base.html" %}

{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'Platform/css/home.css' %}">
  <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
{% endblock %}

{% block title %}{{ user.username }} - Eventos Organizando{% endblock %}

{% block body %}
    <div class="container custom-container ">
        {% if messages %}
        <br>
        <ul class="messages">
            {% for message in messages %}
              <div class="{{ message.tags }}" role="alert">
                {{ message|safe }}
              </div>
            {% endfor %}
        </ul>
      {% endif %}
        <br>
      <h1><u>{{ user.username }} - Eventos Organizando</h1>
      <p style="float: right;"><i title="Quantidade total de eventos em que o usuário está participando" class="bi bi-diamond-fill"></i> {{ events_organizing.count }}</p> <br>
      <hr><br>

      {% for event in events_organizing %}
      <div class="row">
        <div class="col-12">
            <div class="card {% if event.has_passed %}has_passed {% else %} custom-mini-card{% endif %} " style="max-width: 100%; margin-bottom: 0.25rem;">
                <div class="card-body">
              <div class="row align-items-center">
                <div class="col-2">
                  <a href="{{event.event_banner.url}}"><img width="40px" src="{{ event.event_banner.url }}" alt="Imagem do usuário" class="img-fluid"></a>
                </div>
                <div class="col-6">
                  <p class="card-text d-inline texts-container" style="margin-right: 2rem; margin-left: 0;"><a class="link" href="{% url 'ver_mais' event.id %}">{{ event.title }}</a></p>
                </div>
                <div class="col-4 text-right">
                    <a class="btn cta-button" href="{% url 'ver_mais' event.id %}">Ver Mais</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
    <div class="row">
      <h2>{{ user.username }} não organiza nenhum evento.</h2>
    </div>
    {% endfor %}
</div>

    
{% endblock %}