core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secretadmin/', admin.site.urls),
    path('', include('Platform.urls')),
    path('eventos/', include('eventos.urls')),
    path('accounts/', include('account_manager.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('organizando/', views.organizando, name='organizando'),
    path('organizando/criar_evento/', views.criar_evento, name='criar_evento'),
    path('organizando/editar_event/<int:event_id>/', views.editar_evento, name='editar_evento'),
    path('organizando/remover_event_banner/<int:event_id>/', views.remover_event_banner, name='remover_event_banner'),
    path('organizando/<int:event_id>/excluir/', views.excluir_evento, name='excluir_evento'),
    path('organizando/solicitacoes_evento/<int:event_id>/', views.solicitacoes_evento, name='solicitacoes_evento'),
    path('organizando/solicitacoes_evento/<int:event_id>/rejeitar_solicitacao/<int:id_user_solicitation>/',views.rejeitar_solicitacao, name='rejeitar_solicitacao'),
    path('organizando/solicitacoes_evento/<int:event_id>/aceitar_solicitacao/<int:id_user_solicitation>/',views.aceitar_solicitacao, name='aceitar_solicitacao'),
    path('participando/<int:render_solicitations>/', views.participando, name='participando'),
    path('participando/sair/<int:event_id>/<int:render_solicitations>/', views.deixar_evento, name='deixar_evento'),
    path('ver_mais/<int:id_event>/', views.ver_mais, name='ver_mais'),
    path('ver_mais/<int:event_id>/participantes/', views.participantes, name='participantes'),
    path('ver_mais/<int:event_id>/participantes/remover_participante/<int:participant_id>/', views.remover_participante, name='remover_participante'),
    path('participar/<int:id_event>/', views.participar, name='participar'),
] 

eventos/models.py
from django.db import models
from account_manager.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone as zone
from django_resized import ResizedImageField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

DEFAULT_EVENT_BANNER = 'event_banners/default_event_banner.png'

class Event(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()

    organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    participants = models.ManyToManyField(User, related_name='event_participants', blank=True)

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)  
    private = models.BooleanField(help_text='definir como True torna preciso a aceitação da requisição de participação')
    free = models.BooleanField(help_text='definir como True significa que é um evento livre, sem restrição de idade')
    start_date_time = models.DateTimeField(default=zone.now)
    final_date_time = models.DateTimeField(default=zone.now)
    event_banner = ResizedImageField(size=[600, 600], quality=85, upload_to='event_banners', default=DEFAULT_EVENT_BANNER)
    
    banned_users = models.ManyToManyField(User, related_name='banned_events', blank=True)
    
    def ban_user(self, user_id):
        try:
            user = User.objects.get(id=user_id)
            self.banned_users.add(user)
            return True
        except ObjectDoesNotExist:
            return False        
    
    def unban_user(self, user_id):
        try:
            user = User.objects.get(id=user_id)
            self.banned_users.remove(user)
            return True
        except ObjectDoesNotExist:
            return False        
    
    def is_banned_user(self, user_id):
        try:
            return self.banned_users.filter(id=user_id).exists()
        except ObjectDoesNotExist:
            return False
    
    @property
    def qtd_solicitations(self):
        return self.solicitation_set.filter(status='w').count()
    
    @property
    def qtd_participants(self):
        return self.participants.all().count()

    def has_passed(self):
        return self.final_date_time < zone.now()

    def accept_user(self, user_id):
        try:
            user = User.objects.get(id=user_id)
            solicitation = self.solicitation_set.get(user_id=user_id)
            solicitation.status = 'a'
            solicitation.save()
            self.participants.add(user)
            return True
        except ObjectDoesNotExist:
            return False
        
    def reject_user(self, user_id):
        try:
            solicitation = self.solicitation_set.get(user_id=user_id)
            solicitation.status = 'r'
            solicitation.save()

            return True
        except ObjectDoesNotExist:
            return False
    
    def remove_user(self, participant_id):
        try:
            user = User.objects.get(id=participant_id)
            self.participants.remove(user)
            
            return True
        except ObjectDoesNotExist:
            return False
                    
    def __str__(self):
        return self.title
    

class Solicitation(models.Model):
    STATUS = (
        ('a', 'Aceito'),
        ('w', 'Aguardando'),
        ('r', 'Rejeitado')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=STATUS, default='w')

    class Meta:
        unique_together = ('user', 'event')

    
    def __str__(self) -> str:
        return (f'u: {self.user} | e: {self.event} | s: {self.status}')

eventos/forms.py
from django import forms
from datetime import datetime
from django.utils import timezone
from .models import Category, Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'category', 'private', 'free', 'start_date_time', 'final_date_time', 'event_banner']

    title = forms.CharField(required=True, label='Título:', max_length=40, widget=forms.TextInput(attrs={'id': 'title', 'class':'form-control', 'aria-describedby':'emailHelp'}))
    description = forms.CharField(required=True, label="Descrição:", widget=forms.Textarea(attrs={'id': 'description','class': 'form-control', 'style': 'height: 100px'}))
    category = forms.ModelChoiceField(required=True, label='Selecione a categoria do evento:', empty_label='Selecione', queryset=Category.objects.all(), widget=forms.Select(attrs={'class': 'form-control custom-form-width'}))
    private = forms.BooleanField(required=False, label='Privado:',widget=forms.CheckboxInput(attrs={'id': 'private','class': 'form-check-label'}))
    free = forms.BooleanField(required=False, label='Para todas as idades:',widget=forms.CheckboxInput(attrs={'id': 'free','class': 'form-check-label'}))
    start_date_time = forms.DateTimeField(required=True, label='Data e hora de início:', widget=forms.DateTimeInput(attrs={'id': 'start_date_time', 'class': 'form-control custom-form-width', 'placeholder': 'dd/mm/aaaa hh:mm'}))
    final_date_time = forms.DateTimeField(required=True, label='Data e hora de término:', widget=forms.DateTimeInput(attrs={'id': 'final_date_time', 'class': 'form-control custom-form-width', 'placeholder': 'dd/mm/aaaa hh:mm'}))
    event_banner = forms.FileField(required=False, label='Banner do evento:', widget=forms.FileInput(attrs={'id': 'event_banner', 'class': 'form-control'}))

    def clean_event_banner(self):
        event_banner = self.cleaned_data['event_banner']
        if not event_banner:
            event_banner = '/event_banners/default_event_banner.png'
        return event_banner

    def clean(self):
        data_atual = timezone.now()
        start_date_time = self.cleaned_data.get('start_date_time')
        final_date_time = self.cleaned_data.get('final_date_time')        
        if start_date_time and final_date_time:
            if start_date_time > final_date_time:
                raise forms.ValidationError('Data inicial não pode ser após a data final do evento.')
            if start_date_time < data_atual or final_date_time < data_atual:
                raise forms.ValidationError('Data informada já passou.')
            if start_date_time == final_date_time:
                raise forms.ValidationError('O evento termina e começa no mesmo momento.')
        return self.cleaned_data

eventos/templates/criar_evento.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">

{% endblock %}

{% block title %}Novo Evento{% endblock %}


{% block body %}
    <div class="container custom-container">
        {% if form.errors %}
        <ul class="errorlist">
          {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
          {% endfor %}
        </ul>

        {% if form.errors %}
            <ul class="errorlist">
            {% for field, errors in form.errors.items %}
                {% if field in form.cleaned_data %}
                    <li>{{ errors }}</li>
                {% endif %}
            {% endfor %}
            </ul>
      {% endif %}
    

      {% endif %}
            <h1>Criar Evento</h1><hr>
        <form action="{% url 'criar_evento' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3">
                <label for="title">{{ form.title.label }}</label>
                {{ form.title }}

                {% if form.title.errors %}
                    <ul class="errorlist">
                        {% for error in form.title.errors %}
                            <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                
            </div>
            
            <div class="mb-3">
                <label for="description">{{ form.description.label }}</label>
                {{ form.description }}
                <div style="color: rgb(159, 159, 159);" id="titlehelp" class="form-text">Dê as informações que achar relevante para alguém que deseja se inscrever para participar.</div>

                {% if form.description.errors %}
                <ul class="errorlist">
                    {% for error in form.description.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>

            <div class="mb-3">
                {{ form.category.label }}
                {{ form.category }}
                {% if form.category.errors %}
                <ul class="errorlist">
                    {% for error in form.category.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>
            <div class="mb-3 form-check">
                <label for="free">{{ form.free.label }}</label>
                {{ form.free }}
                {% if form.free.errors %}
                <ul class="errorlist">
                    {% for error in form.free.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>   

            <div class="mb-3 form-check">
                <label for="private">{{ form.private.label }}</label>
                {{ form.private }}
                <div style="color: rgb(159, 159, 159);" id="titlehelp" class="form-text">selecionar faz com que os usuários que quiserem participar terem que solicitar</div>
                {% if form.private.errors %}
                <ul class="errorlist">
                    {% for error in form.private.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>

            <div class="mb-3">
                <label for="start_date_time">{{ form.start_date_time.label }}</label>
                {{ form.start_date_time }}
                {% if form.start_date_time.errors %}
                <ul class="errorlist">
                    {% for error in form.start_date_time.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>
            <div class="mb-3">
                <label for="final_date_time">{{ form.final_date_time.label }}</label>
                {{ form.final_date_time }}
                {% if form.final_date_time.errors %}
                <ul class="errorlist">
                    {% for error in form.final_date_time.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
        
            </div>
            <div class="mb-3">
                <label for="event_banner">{{ form.event_banner.label }}</label>
                {{ form.event_banner }}
                {% if form.event_banner.errors %}
                <ul class="errorlist">
                    {% for error in form.event_banner.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
          
            </div>
            <hr>            
            <button type="submit" class="btn cta-button">Criar</button>
          </form>
          
    </div>
    
    <!-- Inicialize o DateTimePicker -->
{% endblock %}

eventos/templates/editar_evento.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">

{% endblock %}

{% block title %}Editar Evento{% endblock %}

{% block body %}
    <div class="container custom-container">
        {% if form.errors %}
        <ul class="errorlist">
          {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
          {% endfor %}
        </ul>

        {% if form.errors %}
            <ul class="errorlist">
            {% for field, errors in form.errors.items %}
                {% if field in form.cleaned_data %}
                    <li>{{ errors }}</li>
                {% endif %}
            {% endfor %}
            </ul>
      {% endif %}
    
      {% endif %}
            <h1>Editar Evento</h1><hr>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3">
                <label for="id_event_banner">{{ form.event_banner.label }}:</label> <br>
                <a href="{{ event_banner.url }}">
                    <img class="value-img" src="{{ event_banner.url }}">
                </a> 
            </div>
            <div class="mb-3">
                      <div class="input-group" style="width: 370px;">
                        {% if not event_banner_is_default %}
                        <a class="btn btn-danger delete-btn" href="{% url 'remover_event_banner' event_id %}" title='Remover imagem de usuário' >
                          <i class="bi bi-trash" style="color: white;"></i>
                        </a>
                        {% endif %}
                        {{ form.event_banner }}
                      </div>



                {% if form.event_banner.errors %}
                <ul class="errorlist">
                    {% for error in form.event_banner.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
          
            </div>

            <div class="mb-3">
                <label for="title">{{ form.title.label }}</label>
                {{ form.title }}

                {% if form.title.errors %}
                    <ul class="errorlist">
                        {% for error in form.title.errors %}
                            <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                
            </div>
            
            <div class="mb-3">
                <label for="description">{{ form.description.label }}</label>
                {{ form.description }}
                <div style="color: rgb(159, 159, 159);" id="titlehelp" class="form-text">Dê as informações que achar relevante para alguém que deseja se inscrever para participar.</div>

                {% if form.description.errors %}
                <ul class="errorlist">
                    {% for error in form.description.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>

            <div class="mb-3">
                {{ form.category.label }}:
                {{ form.category }}
                {% if form.category.errors %}
                <ul class="errorlist">
                    {% for error in form.category.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>
            <div class="mb-3 form-check">
                <label for="free">{{ form.free.label }}</label>
                {{ form.free }}
                {% if form.free.errors %}
                <ul class="errorlist">
                    {% for error in form.free.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>   

            <div class="mb-3 form-check">
                <label for="private">{{ form.private.label }}</label>
                {{ form.private }}
                <div style="color: rgb(159, 159, 159);" id="titlehelp" class="form-text">selecionar faz com que os usuários que quiserem participar terem que solicitar</div>
                {% if form.private.errors %}
                <ul class="errorlist">
                    {% for error in form.private.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            </div>

            <div class="mb-3">
                <label for="start_date_time">{{ form.start_date_time.label }}</label>
                {{ form.start_date_time }}
                {% if form.start_date_time.errors %}
                <ul class="errorlist">
                    {% for error in form.start_date_time.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}


            </div>
            <div class="mb-3">
                <label for="final_date_time">{{ form.final_date_time.label }}</label>
                {{ form.final_date_time }}
                {% if form.final_date_time.errors %}
                <ul class="errorlist">
                    {% for error in form.final_date_time.errors %}
                        <li style="color: rgb(229, 70, 70);">{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <hr>
            <button type="submit" class="btn cta-button">Atualizar</button>
            {% comment %} O ideal seria fazer um modal com uma mensagem push para confirmação se o usuário tem realmente certeza de que quer excluir o evento {% endcomment %}
            <a style="float: right;" class="btn btn-danger" href="{% url 'excluir_evento' event_id %}">Excluir evento</a> <br>  
        </form>
          
    </div>
    
    <!-- Inicialize o DateTimePicker -->
{% endblock %}

eventos/templates/organizando.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'Platform/css/home.css' %}">
  <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
{% endblock %}

{% block title %}Meus Eventos - Organizando{% endblock %}

{% block body %}
<header>
    <div class="container">
          <h1>Eventos - Organizando</h1>
        <a href="{% url 'criar_evento' %}" class="cta-button">Organizar novo evento</a>

        <hr>
        <form action="{% url 'organizando' %}" method="post"> {% csrf_token %}
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="include_has_passed" value="True" id="flexCheckDefault" {% if request.POST.include_has_passed %}checked{% endif %}>
            <label class="form-check-label" for="flexCheckDefault">Incluir eventos que já passaram</label>
          </div>

          <button style="padding: 4px; width: 50px;" class="cta-button" type="submit">ir »</button>

        </form>

    </div>
</header>
  <!-- MENSAGENS -->
  {% if messages %}
  <br>
  <ul class="messages">
      {% for message in messages %}
        <div class="{{ message.tags }}" role="alert">
          {{ message|safe }}
        </div>
      {% endfor %}
  </ul>
{% endif %}

<section id="blog" class="blog">
    <div class="container" data-aos="fade-up">
      <div class="row gy-4 posts-list">
        {% for event in my_events %}
        <div class="col-xl-4 col-md-6 custom-card">
          <article class=" {% if event.has_passed %}has_passed{% endif %}">
            <div class="post-img">
              <img src="{{ event.event_banner.url }}" alt="" class="img-fluid custom-img-fluid">
            </div>
            <p class="post-category">
                {{ event.category }}
            </p>

            <h2 class="title">
              <a href="{% url 'ver_mais' event.id %}">{{ event.title }}</a>
            </h2>
            <p class="caracteristica-evento">{% if event.free %}Livre{% else %}+18{% endif %}</p>
            <p class="caracteristica-evento">{% if event.private %}Privado{% else %}Público{% endif %}</p>
            {% if event.has_passed %}<p style="color: red;">Evento já acabou...</p>{% endif %}
            <p class="n-participants"><a class="link" style="text-decoration: none;" href="{% url 'participantes' event.id %}"><i class="bi bi-person-fill"></i> {{ event.qtd_participants }}</a></p>
            <div class="d-flex align-items-center">
              <div class="post-meta">
                <p class="post-date"> 
                  <time datetime="{{ event.start_date_time }}">{{ event.start_date_time|date:"d/m/Y" }}</time>
                </p>
              </div>
            </div><br>
            {% if not event.has_passed %}
              <a href="{% url 'editar_evento' event.id %}" class="cta-button btn-inline btn-edit">Editar</a>
            {% endif %}
            {% if event.private %}
              <a href="{% url 'solicitacoes_evento' event.id %}" class="cta-button btn-inline btn-solicitations"><i style="display: inline;" class="bi bi-envelope-fill"><p style="font-size: small; display: inline;"> {{ event.qtd_solicitations }}</p></i></a>
            {% endif %}

          </article>
        </div>

   {% empty %}
        <h1>Você não está organizando nenhum evento no momento.</h1>

   {% endfor %}
  </div>
    </div>

      <!-- End post list item -->


  </section><!-- End Blog Section -->
{% endblock %}

eventos/templates/participantes.html
{% extends "base/base.html" %}

{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'Platform/css/home.css' %}">
  <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
{% endblock %}

{% block title %}Ver mais - Participantes{% endblock %}

{% block body %}
    <div class="container custom-container ">
        {% if messages %}
        <br>
        <ul class="messages">
            {% for message in messages %}
              <div class="{{ message.tags }}" role="alert">
                {{ message|safe }}
              </div>
            {% endfor %}
        </ul>
      {% endif %}
        <br>
      <h1><u>{{ event.title }}</u> - Participantes</h1>
      <form action="" method="get"> {% csrf_token %}
        <div class="row">
          <div class="col-9">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Pesquisar usuário..." name="search-input">
              <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">Pesquisar</button>
                  <a class="btn btn-secondary" href=".">Limpar</a>
              </div>
            </div>
          </div>
        </div>
      </form>
      <p style="float: right;"><i title="Quantidade total de participantes deste evento" style=" font-size: 26px; text-decoration: none;" class="bi bi-person-fill"></i> {{ qtd_participants }}</p> <br>
      <hr><br>
      {% for participant in participants %}
          <div class="row">
            <div class="col-12">
              <div class="card custom-mini-card" style="max-width: 100%; margin-bottom: 0.25rem;">
                  <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col-2">
                      <a href="{{ participant.user_img.url }}"><img width="40px" src="{{ participant.user_img.url }}" alt="Imagem do usuário" class="img-fluid"></a>
                    </div>
                    <div class="col-6">
                      <a class="link" href="{% url 'ver_perfil' participant.id %}">
                      <p class="card-text d-inline texts-container" style="margin-right: 2rem; margin-left: 0;">{{ participant.username }}</p>
                      </a>
                    </div>
                    {% if user_is_organizer and not event.has_passed %}
                        <div class="col-4 text-right">
                            <a class="btn btn-danger" href="{% url 'remover_participante' event.id participant.id %}">Expulsar</a>
                        </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% empty %}
        <div class="row">
          <h2>Nenhuma participante encontrado.</h2>
        </div>
        {% endfor %}
    </div>
{% endblock %}

eventos/templates/solicitacoes_evento.html
{% extends "base/base.html" %}

{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'Platform/css/home.css' %}">
  <link rel="stylesheet" href="{% static 'eventos/css/eventos.css' %}">
{% endblock %}

{% block title %}Organizando - Solcitações{% endblock %}

{% block body %}

    <div class="container custom-container ">
          {% if messages %}
          <br>
          <ul class="messages">
              {% for message in messages %}
                <div class="{{ message.tags }}" role="alert">
                  {{ message|safe }}
                </div>
              {% endfor %}
          </ul>
        {% endif %}
          <br>
        <h1><u>{{ event_title }}</u> - Solicitações</h1>
        <form action="" method="get"> {% csrf_token %}
        <div class="row">
          <div class="col-9">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Pesquisar usuário..." name="search-input">
              <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">Pesquisar</button>
                  <a class="btn btn-secondary" href=".">Limpar</a>
              </div>
            </div>
          </div>
          <div class="col-3">
            <div class="col-9 d-flex align-items-center">
              <label for="filter-select" class="mr-2">Filtre: </label>
              <select id="filter-select" class="form-control" name="status_select"> 
                  <option value="w" {% if request.GET.status_select == 'w' %}selected{% endif %}>Aguardando</option>
                  <option value="a" {% if request.GET.status_select == 'a' %}selected{% endif %}>Aceitas</option>
                  <option value="r" {% if request.GET.status_select == 'r' %}selected{% endif %}>Rejeitadas</option>
              </select>
            </div>
          </div>
        </div>
    </form>
    <p style="float: right;"><i title="Quantidade total de solicitações aguardando por resposta deste evento" style=" font-size: 26px; text-decoration: none;" class="bi bi-person-fill"></i> {{ solicitations.count }}</p> <br>
        <hr><br>
        {% for solicitation in solicitations %}
            <div class="row">
              <div class="col-12">
                <div class="card custom-mini-card" style="max-width: 100%; margin-bottom: 0.25rem;">
                    <div class="card-body">
                    <div class="row align-items-center">
                      <div class="col-2">
                        <a href="{{ solicitation.user.user_img.url }}"><img width="40px" src="{{ solicitation.user.user_img.url }}" alt="Imagem do usuário que solcitou a participação" class="img-fluid"></a>
                      </div>
                      <div class="col-6">
                        <p class="card-text d-inline texts-container" style="margin-right: 2rem; margin-left: 0;">{{ solicitation.user.username }}</p>
                        <p class="card-text d-inline {{ solicitation.status }}" >{{ solicitation.get_status_display }}</p>
                      </div>
                      <div class="col-4 text-right">
                        {% if not solicitation.event.has_passed %}
                          {% if not solicitation.status == 'r' and not solicitation.status == 'a' %}
                            <a class="btn btn-danger" href="{% url 'rejeitar_solicitacao' solicitation.event.id solicitation.user.id %}">Rejeitar</a>
                          {% endif %}
                          {% if not solicitation.status == 'a' %}
                            <a class="btn btn-success" href="{% url 'aceitar_solicitacao' solicitation.event.id solicitation.user.id %}">Aceitar</a>
                          {% endif %}
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>  
          {% empty %}
          <div class="row">
            <h2>Nenhuma solicitação encontrada.</h2>
          </div>
          {% endfor %}
    </div>
{% endblock %}